// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: news/v1/news.proto

package newsv1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NewsService_SaveProcessedNews_FullMethodName     = "/news.v1.NewsService/SaveProcessedNews"
	NewsService_GetActiveAlertRules_FullMethodName   = "/news.v1.NewsService/GetActiveAlertRules"
	NewsService_ReserveAlertDelivery_FullMethodName  = "/news.v1.NewsService/ReserveAlertDelivery"
	NewsService_FinalizeAlertDelivery_FullMethodName = "/news.v1.NewsService/FinalizeAlertDelivery"
)

// NewsServiceClient is the client API for NewsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NewsService предоставляет методы для работы с обработанными новостями.
// Используется news-processor для сохранения новостей через main-service.
type NewsServiceClient interface {
	// SaveProcessedNews сохраняет пачку обработанных новостей в PostgreSQL.
	// Дедупликация по URL на уровне БД: повторные URL игнорируются без ошибки.
	//
	// @Router /news.v1.NewsService/SaveProcessedNews [post].
	SaveProcessedNews(ctx context.Context, in *SaveProcessedNewsRequest, opts ...grpc.CallOption) (*SaveProcessedNewsResponse, error)
	// GetActiveAlertRules возвращает активные правила алертинга.
	// Используется news-processor для матчинга ключевых слов.
	//
	// @Router /news.v1.NewsService/GetActiveAlertRules [post].
	GetActiveAlertRules(ctx context.Context, in *GetActiveAlertRulesRequest, opts ...grpc.CallOption) (*GetActiveAlertRulesResponse, error)
	// ReserveAlertDelivery резервирует доставку алерта: дедуп + cooldown + pending.
	// Если should_send=false, доставку выполнять не нужно.
	//
	// @Router /news.v1.NewsService/ReserveAlertDelivery [post].
	ReserveAlertDelivery(ctx context.Context, in *ReserveAlertDeliveryRequest, opts ...grpc.CallOption) (*ReserveAlertDeliveryResponse, error)
	// FinalizeAlertDelivery фиксирует финальный статус доставки алерта.
	//
	// @Router /news.v1.NewsService/FinalizeAlertDelivery [post].
	FinalizeAlertDelivery(ctx context.Context, in *FinalizeAlertDeliveryRequest, opts ...grpc.CallOption) (*FinalizeAlertDeliveryResponse, error)
}

type newsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNewsServiceClient(cc grpc.ClientConnInterface) NewsServiceClient {
	return &newsServiceClient{cc}
}

func (c *newsServiceClient) SaveProcessedNews(ctx context.Context, in *SaveProcessedNewsRequest, opts ...grpc.CallOption) (*SaveProcessedNewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveProcessedNewsResponse)
	err := c.cc.Invoke(ctx, NewsService_SaveProcessedNews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsServiceClient) GetActiveAlertRules(ctx context.Context, in *GetActiveAlertRulesRequest, opts ...grpc.CallOption) (*GetActiveAlertRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActiveAlertRulesResponse)
	err := c.cc.Invoke(ctx, NewsService_GetActiveAlertRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsServiceClient) ReserveAlertDelivery(ctx context.Context, in *ReserveAlertDeliveryRequest, opts ...grpc.CallOption) (*ReserveAlertDeliveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveAlertDeliveryResponse)
	err := c.cc.Invoke(ctx, NewsService_ReserveAlertDelivery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsServiceClient) FinalizeAlertDelivery(ctx context.Context, in *FinalizeAlertDeliveryRequest, opts ...grpc.CallOption) (*FinalizeAlertDeliveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinalizeAlertDeliveryResponse)
	err := c.cc.Invoke(ctx, NewsService_FinalizeAlertDelivery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NewsServiceServer is the server API for NewsService service.
// All implementations must embed UnimplementedNewsServiceServer
// for forward compatibility.
//
// NewsService предоставляет методы для работы с обработанными новостями.
// Используется news-processor для сохранения новостей через main-service.
type NewsServiceServer interface {
	// SaveProcessedNews сохраняет пачку обработанных новостей в PostgreSQL.
	// Дедупликация по URL на уровне БД: повторные URL игнорируются без ошибки.
	//
	// @Router /news.v1.NewsService/SaveProcessedNews [post].
	SaveProcessedNews(context.Context, *SaveProcessedNewsRequest) (*SaveProcessedNewsResponse, error)
	// GetActiveAlertRules возвращает активные правила алертинга.
	// Используется news-processor для матчинга ключевых слов.
	//
	// @Router /news.v1.NewsService/GetActiveAlertRules [post].
	GetActiveAlertRules(context.Context, *GetActiveAlertRulesRequest) (*GetActiveAlertRulesResponse, error)
	// ReserveAlertDelivery резервирует доставку алерта: дедуп + cooldown + pending.
	// Если should_send=false, доставку выполнять не нужно.
	//
	// @Router /news.v1.NewsService/ReserveAlertDelivery [post].
	ReserveAlertDelivery(context.Context, *ReserveAlertDeliveryRequest) (*ReserveAlertDeliveryResponse, error)
	// FinalizeAlertDelivery фиксирует финальный статус доставки алерта.
	//
	// @Router /news.v1.NewsService/FinalizeAlertDelivery [post].
	FinalizeAlertDelivery(context.Context, *FinalizeAlertDeliveryRequest) (*FinalizeAlertDeliveryResponse, error)
	mustEmbedUnimplementedNewsServiceServer()
}

// UnimplementedNewsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNewsServiceServer struct{}

func (UnimplementedNewsServiceServer) SaveProcessedNews(context.Context, *SaveProcessedNewsRequest) (*SaveProcessedNewsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveProcessedNews not implemented")
}

func (UnimplementedNewsServiceServer) GetActiveAlertRules(context.Context, *GetActiveAlertRulesRequest) (*GetActiveAlertRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveAlertRules not implemented")
}

func (UnimplementedNewsServiceServer) ReserveAlertDelivery(context.Context, *ReserveAlertDeliveryRequest) (*ReserveAlertDeliveryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReserveAlertDelivery not implemented")
}

func (UnimplementedNewsServiceServer) FinalizeAlertDelivery(context.Context, *FinalizeAlertDeliveryRequest) (*FinalizeAlertDeliveryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FinalizeAlertDelivery not implemented")
}
func (UnimplementedNewsServiceServer) mustEmbedUnimplementedNewsServiceServer() {}
func (UnimplementedNewsServiceServer) testEmbeddedByValue()                     {}

// UnsafeNewsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NewsServiceServer will
// result in compilation errors.
type UnsafeNewsServiceServer interface {
	mustEmbedUnimplementedNewsServiceServer()
}

func RegisterNewsServiceServer(s grpc.ServiceRegistrar, srv NewsServiceServer) {
	// If the following call panics, it indicates UnimplementedNewsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NewsService_ServiceDesc, srv)
}

func _NewsService_SaveProcessedNews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveProcessedNewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsServiceServer).SaveProcessedNews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsService_SaveProcessedNews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsServiceServer).SaveProcessedNews(ctx, req.(*SaveProcessedNewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsService_GetActiveAlertRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveAlertRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsServiceServer).GetActiveAlertRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsService_GetActiveAlertRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsServiceServer).GetActiveAlertRules(ctx, req.(*GetActiveAlertRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsService_ReserveAlertDelivery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveAlertDeliveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsServiceServer).ReserveAlertDelivery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsService_ReserveAlertDelivery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsServiceServer).ReserveAlertDelivery(ctx, req.(*ReserveAlertDeliveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsService_FinalizeAlertDelivery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeAlertDeliveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsServiceServer).FinalizeAlertDelivery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsService_FinalizeAlertDelivery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsServiceServer).FinalizeAlertDelivery(ctx, req.(*FinalizeAlertDeliveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NewsService_ServiceDesc is the grpc.ServiceDesc for NewsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NewsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "news.v1.NewsService",
	HandlerType: (*NewsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveProcessedNews",
			Handler:    _NewsService_SaveProcessedNews_Handler,
		},
		{
			MethodName: "GetActiveAlertRules",
			Handler:    _NewsService_GetActiveAlertRules_Handler,
		},
		{
			MethodName: "ReserveAlertDelivery",
			Handler:    _NewsService_ReserveAlertDelivery_Handler,
		},
		{
			MethodName: "FinalizeAlertDelivery",
			Handler:    _NewsService_FinalizeAlertDelivery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "news/v1/news.proto",
}
