// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: news/v1/news.proto

package newsv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProcessedNewsItem — обработанная новость для сохранения.
type ProcessedNewsItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUID
	SourceId      string                 `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	PublishedAt   int64                  `protobuf:"varint,8,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"` // Unix timestamp (секунды)
	ProcessedAt   int64                  `protobuf:"varint,9,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"` // Unix timestamp (секунды)
	S3Key         string                 `protobuf:"bytes,10,opt,name=s3_key,json=s3Key,proto3" json:"s3_key,omitempty"`                   // Ключ объекта с артефактом в S3-совместимом хранилище
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessedNewsItem) Reset() {
	*x = ProcessedNewsItem{}
	mi := &file_news_v1_news_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessedNewsItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessedNewsItem) ProtoMessage() {}

func (x *ProcessedNewsItem) ProtoReflect() protoreflect.Message {
	mi := &file_news_v1_news_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessedNewsItem.ProtoReflect.Descriptor instead.
func (*ProcessedNewsItem) Descriptor() ([]byte, []int) {
	return file_news_v1_news_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessedNewsItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProcessedNewsItem) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *ProcessedNewsItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProcessedNewsItem) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ProcessedNewsItem) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ProcessedNewsItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ProcessedNewsItem) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ProcessedNewsItem) GetPublishedAt() int64 {
	if x != nil {
		return x.PublishedAt
	}
	return 0
}

func (x *ProcessedNewsItem) GetProcessedAt() int64 {
	if x != nil {
		return x.ProcessedAt
	}
	return 0
}

func (x *ProcessedNewsItem) GetS3Key() string {
	if x != nil {
		return x.S3Key
	}
	return ""
}

// SaveProcessedNewsRequest содержит пачку новостей для сохранения.
type SaveProcessedNewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	News          []*ProcessedNewsItem   `protobuf:"bytes,1,rep,name=news,proto3" json:"news,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveProcessedNewsRequest) Reset() {
	*x = SaveProcessedNewsRequest{}
	mi := &file_news_v1_news_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveProcessedNewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveProcessedNewsRequest) ProtoMessage() {}

func (x *SaveProcessedNewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_news_v1_news_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveProcessedNewsRequest.ProtoReflect.Descriptor instead.
func (*SaveProcessedNewsRequest) Descriptor() ([]byte, []int) {
	return file_news_v1_news_proto_rawDescGZIP(), []int{1}
}

func (x *SaveProcessedNewsRequest) GetNews() []*ProcessedNewsItem {
	if x != nil {
		return x.News
	}
	return nil
}

// SaveProcessedNewsResponse возвращает количество реально сохранённых новостей.
type SaveProcessedNewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SavedCount    int32                  `protobuf:"varint,1,opt,name=saved_count,json=savedCount,proto3" json:"saved_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveProcessedNewsResponse) Reset() {
	*x = SaveProcessedNewsResponse{}
	mi := &file_news_v1_news_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveProcessedNewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveProcessedNewsResponse) ProtoMessage() {}

func (x *SaveProcessedNewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_news_v1_news_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveProcessedNewsResponse.ProtoReflect.Descriptor instead.
func (*SaveProcessedNewsResponse) Descriptor() ([]byte, []int) {
	return file_news_v1_news_proto_rawDescGZIP(), []int{2}
}

func (x *SaveProcessedNewsResponse) GetSavedCount() int32 {
	if x != nil {
		return x.SavedCount
	}
	return 0
}

// AlertRule — минимальная проекция правила для матчинга в news-processor.
type AlertRule struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserUuid        string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	Keyword         string                 `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	CooldownSeconds int32                  `protobuf:"varint,4,opt,name=cooldown_seconds,json=cooldownSeconds,proto3" json:"cooldown_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AlertRule) Reset() {
	*x = AlertRule{}
	mi := &file_news_v1_news_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertRule) ProtoMessage() {}

func (x *AlertRule) ProtoReflect() protoreflect.Message {
	mi := &file_news_v1_news_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertRule.ProtoReflect.Descriptor instead.
func (*AlertRule) Descriptor() ([]byte, []int) {
	return file_news_v1_news_proto_rawDescGZIP(), []int{3}
}

func (x *AlertRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AlertRule) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *AlertRule) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *AlertRule) GetCooldownSeconds() int32 {
	if x != nil {
		return x.CooldownSeconds
	}
	return 0
}

// GetActiveAlertRulesRequest — запрос активных правил.
type GetActiveAlertRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveAlertRulesRequest) Reset() {
	*x = GetActiveAlertRulesRequest{}
	mi := &file_news_v1_news_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveAlertRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveAlertRulesRequest) ProtoMessage() {}

func (x *GetActiveAlertRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_news_v1_news_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveAlertRulesRequest.ProtoReflect.Descriptor instead.
func (*GetActiveAlertRulesRequest) Descriptor() ([]byte, []int) {
	return file_news_v1_news_proto_rawDescGZIP(), []int{4}
}

// GetActiveAlertRulesResponse — ответ со списком активных правил.
type GetActiveAlertRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*AlertRule           `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveAlertRulesResponse) Reset() {
	*x = GetActiveAlertRulesResponse{}
	mi := &file_news_v1_news_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveAlertRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveAlertRulesResponse) ProtoMessage() {}

func (x *GetActiveAlertRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_news_v1_news_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveAlertRulesResponse.ProtoReflect.Descriptor instead.
func (*GetActiveAlertRulesResponse) Descriptor() ([]byte, []int) {
	return file_news_v1_news_proto_rawDescGZIP(), []int{5}
}

func (x *GetActiveAlertRulesResponse) GetRules() []*AlertRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

// ReserveAlertDeliveryRequest — запрос на резервирование доставки.
type ReserveAlertDeliveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	RuleId        string                 `protobuf:"bytes,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	UserUuid      string                 `protobuf:"bytes,3,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	NewsId        string                 `protobuf:"bytes,4,opt,name=news_id,json=newsId,proto3" json:"news_id,omitempty"`
	Keyword       string                 `protobuf:"bytes,5,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveAlertDeliveryRequest) Reset() {
	*x = ReserveAlertDeliveryRequest{}
	mi := &file_news_v1_news_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveAlertDeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveAlertDeliveryRequest) ProtoMessage() {}

func (x *ReserveAlertDeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_news_v1_news_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveAlertDeliveryRequest.ProtoReflect.Descriptor instead.
func (*ReserveAlertDeliveryRequest) Descriptor() ([]byte, []int) {
	return file_news_v1_news_proto_rawDescGZIP(), []int{6}
}

func (x *ReserveAlertDeliveryRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ReserveAlertDeliveryRequest) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *ReserveAlertDeliveryRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *ReserveAlertDeliveryRequest) GetNewsId() string {
	if x != nil {
		return x.NewsId
	}
	return ""
}

func (x *ReserveAlertDeliveryRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

// ReserveAlertDeliveryResponse — результат резервирования.
type ReserveAlertDeliveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShouldSend    bool                   `protobuf:"varint,1,opt,name=should_send,json=shouldSend,proto3" json:"should_send,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // duplicate, cooldown, ready
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveAlertDeliveryResponse) Reset() {
	*x = ReserveAlertDeliveryResponse{}
	mi := &file_news_v1_news_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveAlertDeliveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveAlertDeliveryResponse) ProtoMessage() {}

func (x *ReserveAlertDeliveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_news_v1_news_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveAlertDeliveryResponse.ProtoReflect.Descriptor instead.
func (*ReserveAlertDeliveryResponse) Descriptor() ([]byte, []int) {
	return file_news_v1_news_proto_rawDescGZIP(), []int{7}
}

func (x *ReserveAlertDeliveryResponse) GetShouldSend() bool {
	if x != nil {
		return x.ShouldSend
	}
	return false
}

func (x *ReserveAlertDeliveryResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// FinalizeAlertDeliveryRequest — финализация доставки.
type FinalizeAlertDeliveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // sent, failed, dropped
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	SentAtUnix    int64                  `protobuf:"varint,4,opt,name=sent_at_unix,json=sentAtUnix,proto3" json:"sent_at_unix,omitempty"` // unix seconds, only for sent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeAlertDeliveryRequest) Reset() {
	*x = FinalizeAlertDeliveryRequest{}
	mi := &file_news_v1_news_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeAlertDeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeAlertDeliveryRequest) ProtoMessage() {}

func (x *FinalizeAlertDeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_news_v1_news_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeAlertDeliveryRequest.ProtoReflect.Descriptor instead.
func (*FinalizeAlertDeliveryRequest) Descriptor() ([]byte, []int) {
	return file_news_v1_news_proto_rawDescGZIP(), []int{8}
}

func (x *FinalizeAlertDeliveryRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *FinalizeAlertDeliveryRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FinalizeAlertDeliveryRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *FinalizeAlertDeliveryRequest) GetSentAtUnix() int64 {
	if x != nil {
		return x.SentAtUnix
	}
	return 0
}

// FinalizeAlertDeliveryResponse — пустой ответ.
type FinalizeAlertDeliveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeAlertDeliveryResponse) Reset() {
	*x = FinalizeAlertDeliveryResponse{}
	mi := &file_news_v1_news_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeAlertDeliveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeAlertDeliveryResponse) ProtoMessage() {}

func (x *FinalizeAlertDeliveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_news_v1_news_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeAlertDeliveryResponse.ProtoReflect.Descriptor instead.
func (*FinalizeAlertDeliveryResponse) Descriptor() ([]byte, []int) {
	return file_news_v1_news_proto_rawDescGZIP(), []int{9}
}

var File_news_v1_news_proto protoreflect.FileDescriptor

const file_news_v1_news_proto_rawDesc = "" +
	"\n" +
	"\x12news/v1/news.proto\x12\anews.v1\"\x8f\x02\n" +
	"\x11ProcessedNewsItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\tR\bsourceId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12!\n" +
	"\fpublished_at\x18\b \x01(\x03R\vpublishedAt\x12!\n" +
	"\fprocessed_at\x18\t \x01(\x03R\vprocessedAt\x12\x15\n" +
	"\x06s3_key\x18\n" +
	" \x01(\tR\x05s3Key\"J\n" +
	"\x18SaveProcessedNewsRequest\x12.\n" +
	"\x04news\x18\x01 \x03(\v2\x1a.news.v1.ProcessedNewsItemR\x04news\"<\n" +
	"\x19SaveProcessedNewsResponse\x12\x1f\n" +
	"\vsaved_count\x18\x01 \x01(\x05R\n" +
	"savedCount\"}\n" +
	"\tAlertRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\x12)\n" +
	"\x10cooldown_seconds\x18\x04 \x01(\x05R\x0fcooldownSeconds\"\x1c\n" +
	"\x1aGetActiveAlertRulesRequest\"G\n" +
	"\x1bGetActiveAlertRulesResponse\x12(\n" +
	"\x05rules\x18\x01 \x03(\v2\x12.news.v1.AlertRuleR\x05rules\"\xa1\x01\n" +
	"\x1bReserveAlertDeliveryRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\arule_id\x18\x02 \x01(\tR\x06ruleId\x12\x1b\n" +
	"\tuser_uuid\x18\x03 \x01(\tR\buserUuid\x12\x17\n" +
	"\anews_id\x18\x04 \x01(\tR\x06newsId\x12\x18\n" +
	"\akeyword\x18\x05 \x01(\tR\akeyword\"W\n" +
	"\x1cReserveAlertDeliveryResponse\x12\x1f\n" +
	"\vshould_send\x18\x01 \x01(\bR\n" +
	"shouldSend\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x98\x01\n" +
	"\x1cFinalizeAlertDeliveryRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12 \n" +
	"\fsent_at_unix\x18\x04 \x01(\x03R\n" +
	"sentAtUnix\"\x1f\n" +
	"\x1dFinalizeAlertDeliveryResponse2\x98\x03\n" +
	"\vNewsService\x12Z\n" +
	"\x11SaveProcessedNews\x12!.news.v1.SaveProcessedNewsRequest\x1a\".news.v1.SaveProcessedNewsResponse\x12`\n" +
	"\x13GetActiveAlertRules\x12#.news.v1.GetActiveAlertRulesRequest\x1a$.news.v1.GetActiveAlertRulesResponse\x12c\n" +
	"\x14ReserveAlertDelivery\x12$.news.v1.ReserveAlertDeliveryRequest\x1a%.news.v1.ReserveAlertDeliveryResponse\x12f\n" +
	"\x15FinalizeAlertDelivery\x12%.news.v1.FinalizeAlertDeliveryRequest\x1a&.news.v1.FinalizeAlertDeliveryResponseB5Z3github.com/FischukSergey/otus-ms/pkg/news/v1;newsv1b\x06proto3"

var (
	file_news_v1_news_proto_rawDescOnce sync.Once
	file_news_v1_news_proto_rawDescData []byte
)

func file_news_v1_news_proto_rawDescGZIP() []byte {
	file_news_v1_news_proto_rawDescOnce.Do(func() {
		file_news_v1_news_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_news_v1_news_proto_rawDesc), len(file_news_v1_news_proto_rawDesc)))
	})
	return file_news_v1_news_proto_rawDescData
}

var (
	file_news_v1_news_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
	file_news_v1_news_proto_goTypes  = []any{
		(*ProcessedNewsItem)(nil),             // 0: news.v1.ProcessedNewsItem
		(*SaveProcessedNewsRequest)(nil),      // 1: news.v1.SaveProcessedNewsRequest
		(*SaveProcessedNewsResponse)(nil),     // 2: news.v1.SaveProcessedNewsResponse
		(*AlertRule)(nil),                     // 3: news.v1.AlertRule
		(*GetActiveAlertRulesRequest)(nil),    // 4: news.v1.GetActiveAlertRulesRequest
		(*GetActiveAlertRulesResponse)(nil),   // 5: news.v1.GetActiveAlertRulesResponse
		(*ReserveAlertDeliveryRequest)(nil),   // 6: news.v1.ReserveAlertDeliveryRequest
		(*ReserveAlertDeliveryResponse)(nil),  // 7: news.v1.ReserveAlertDeliveryResponse
		(*FinalizeAlertDeliveryRequest)(nil),  // 8: news.v1.FinalizeAlertDeliveryRequest
		(*FinalizeAlertDeliveryResponse)(nil), // 9: news.v1.FinalizeAlertDeliveryResponse
	}
)

var file_news_v1_news_proto_depIdxs = []int32{
	0, // 0: news.v1.SaveProcessedNewsRequest.news:type_name -> news.v1.ProcessedNewsItem
	3, // 1: news.v1.GetActiveAlertRulesResponse.rules:type_name -> news.v1.AlertRule
	1, // 2: news.v1.NewsService.SaveProcessedNews:input_type -> news.v1.SaveProcessedNewsRequest
	4, // 3: news.v1.NewsService.GetActiveAlertRules:input_type -> news.v1.GetActiveAlertRulesRequest
	6, // 4: news.v1.NewsService.ReserveAlertDelivery:input_type -> news.v1.ReserveAlertDeliveryRequest
	8, // 5: news.v1.NewsService.FinalizeAlertDelivery:input_type -> news.v1.FinalizeAlertDeliveryRequest
	2, // 6: news.v1.NewsService.SaveProcessedNews:output_type -> news.v1.SaveProcessedNewsResponse
	5, // 7: news.v1.NewsService.GetActiveAlertRules:output_type -> news.v1.GetActiveAlertRulesResponse
	7, // 8: news.v1.NewsService.ReserveAlertDelivery:output_type -> news.v1.ReserveAlertDeliveryResponse
	9, // 9: news.v1.NewsService.FinalizeAlertDelivery:output_type -> news.v1.FinalizeAlertDeliveryResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_news_v1_news_proto_init() }
func file_news_v1_news_proto_init() {
	if File_news_v1_news_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_news_v1_news_proto_rawDesc), len(file_news_v1_news_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_news_v1_news_proto_goTypes,
		DependencyIndexes: file_news_v1_news_proto_depIdxs,
		MessageInfos:      file_news_v1_news_proto_msgTypes,
	}.Build()
	File_news_v1_news_proto = out.File
	file_news_v1_news_proto_goTypes = nil
	file_news_v1_news_proto_depIdxs = nil
}
