// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: news/v1/news.proto

package newsv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProcessedNewsItem — обработанная новость для сохранения.
type ProcessedNewsItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUID
	SourceId      string                 `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	PublishedAt   int64                  `protobuf:"varint,8,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"` // Unix timestamp (секунды)
	ProcessedAt   int64                  `protobuf:"varint,9,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"` // Unix timestamp (секунды)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessedNewsItem) Reset() {
	*x = ProcessedNewsItem{}
	mi := &file_news_v1_news_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessedNewsItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessedNewsItem) ProtoMessage() {}

func (x *ProcessedNewsItem) ProtoReflect() protoreflect.Message {
	mi := &file_news_v1_news_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessedNewsItem.ProtoReflect.Descriptor instead.
func (*ProcessedNewsItem) Descriptor() ([]byte, []int) {
	return file_news_v1_news_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessedNewsItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProcessedNewsItem) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *ProcessedNewsItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProcessedNewsItem) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ProcessedNewsItem) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ProcessedNewsItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ProcessedNewsItem) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ProcessedNewsItem) GetPublishedAt() int64 {
	if x != nil {
		return x.PublishedAt
	}
	return 0
}

func (x *ProcessedNewsItem) GetProcessedAt() int64 {
	if x != nil {
		return x.ProcessedAt
	}
	return 0
}

// SaveProcessedNewsRequest содержит пачку новостей для сохранения.
type SaveProcessedNewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	News          []*ProcessedNewsItem   `protobuf:"bytes,1,rep,name=news,proto3" json:"news,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveProcessedNewsRequest) Reset() {
	*x = SaveProcessedNewsRequest{}
	mi := &file_news_v1_news_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveProcessedNewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveProcessedNewsRequest) ProtoMessage() {}

func (x *SaveProcessedNewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_news_v1_news_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveProcessedNewsRequest.ProtoReflect.Descriptor instead.
func (*SaveProcessedNewsRequest) Descriptor() ([]byte, []int) {
	return file_news_v1_news_proto_rawDescGZIP(), []int{1}
}

func (x *SaveProcessedNewsRequest) GetNews() []*ProcessedNewsItem {
	if x != nil {
		return x.News
	}
	return nil
}

// SaveProcessedNewsResponse возвращает количество реально сохранённых новостей.
type SaveProcessedNewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SavedCount    int32                  `protobuf:"varint,1,opt,name=saved_count,json=savedCount,proto3" json:"saved_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveProcessedNewsResponse) Reset() {
	*x = SaveProcessedNewsResponse{}
	mi := &file_news_v1_news_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveProcessedNewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveProcessedNewsResponse) ProtoMessage() {}

func (x *SaveProcessedNewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_news_v1_news_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveProcessedNewsResponse.ProtoReflect.Descriptor instead.
func (*SaveProcessedNewsResponse) Descriptor() ([]byte, []int) {
	return file_news_v1_news_proto_rawDescGZIP(), []int{2}
}

func (x *SaveProcessedNewsResponse) GetSavedCount() int32 {
	if x != nil {
		return x.SavedCount
	}
	return 0
}

var File_news_v1_news_proto protoreflect.FileDescriptor

const file_news_v1_news_proto_rawDesc = "" +
	"\n" +
	"\x12news/v1/news.proto\x12\anews.v1\"\xf8\x01\n" +
	"\x11ProcessedNewsItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\tR\bsourceId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12!\n" +
	"\fpublished_at\x18\b \x01(\x03R\vpublishedAt\x12!\n" +
	"\fprocessed_at\x18\t \x01(\x03R\vprocessedAt\"J\n" +
	"\x18SaveProcessedNewsRequest\x12.\n" +
	"\x04news\x18\x01 \x03(\v2\x1a.news.v1.ProcessedNewsItemR\x04news\"<\n" +
	"\x19SaveProcessedNewsResponse\x12\x1f\n" +
	"\vsaved_count\x18\x01 \x01(\x05R\n" +
	"savedCount2i\n" +
	"\vNewsService\x12Z\n" +
	"\x11SaveProcessedNews\x12!.news.v1.SaveProcessedNewsRequest\x1a\".news.v1.SaveProcessedNewsResponseB5Z3github.com/FischukSergey/otus-ms/pkg/news/v1;newsv1b\x06proto3"

var (
	file_news_v1_news_proto_rawDescOnce sync.Once
	file_news_v1_news_proto_rawDescData []byte
)

func file_news_v1_news_proto_rawDescGZIP() []byte {
	file_news_v1_news_proto_rawDescOnce.Do(func() {
		file_news_v1_news_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_news_v1_news_proto_rawDesc), len(file_news_v1_news_proto_rawDesc)))
	})
	return file_news_v1_news_proto_rawDescData
}

var (
	file_news_v1_news_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
	file_news_v1_news_proto_goTypes  = []any{
		(*ProcessedNewsItem)(nil),         // 0: news.v1.ProcessedNewsItem
		(*SaveProcessedNewsRequest)(nil),  // 1: news.v1.SaveProcessedNewsRequest
		(*SaveProcessedNewsResponse)(nil), // 2: news.v1.SaveProcessedNewsResponse
	}
)

var file_news_v1_news_proto_depIdxs = []int32{
	0, // 0: news.v1.SaveProcessedNewsRequest.news:type_name -> news.v1.ProcessedNewsItem
	1, // 1: news.v1.NewsService.SaveProcessedNews:input_type -> news.v1.SaveProcessedNewsRequest
	2, // 2: news.v1.NewsService.SaveProcessedNews:output_type -> news.v1.SaveProcessedNewsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_news_v1_news_proto_init() }
func file_news_v1_news_proto_init() {
	if File_news_v1_news_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_news_v1_news_proto_rawDesc), len(file_news_v1_news_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_news_v1_news_proto_goTypes,
		DependencyIndexes: file_news_v1_news_proto_depIdxs,
		MessageInfos:      file_news_v1_news_proto_msgTypes,
	}.Build()
	File_news_v1_news_proto = out.File
	file_news_v1_news_proto_goTypes = nil
	file_news_v1_news_proto_depIdxs = nil
}
