// Package mainservice GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package mainservice

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "OtusMS Support",
            "url": "https://github.com/FischukSergey/otus-ms"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/news": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает последние новости с полями topic, source и url. Требуется роль admin.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "news"
                ],
                "summary": "Получить список новостей (только admin)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Лимит записей (1..500), по умолчанию 50",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список новостей",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_handlers_newshttp.NewsResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Некорректный query-параметр limit",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_newshttp.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Не авторизован - отсутствует или невалидный JWT токен",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_newshttp.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Доступ запрещён - требуется роль admin",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_newshttp.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_newshttp.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/news/events": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Принимает события view/click/like/dislike/hide для текущего пользователя (роль user/admin).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "personalization"
                ],
                "summary": "Отправить пользовательское событие",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID целевого пользователя (только для admin)",
                        "name": "userUuid",
                        "in": "query"
                    },
                    {
                        "description": "Событие пользователя",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_personalization.CreateEventRequestSchema"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": ""
                    },
                    "400": {
                        "description": "Невалидный payload",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_personalization.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_personalization.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Недостаточно прав",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_personalization.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_personalization.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/news/feed": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает новости с фильтрацией и ранжированием score для текущего пользователя (роль user/admin).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "personalization"
                ],
                "summary": "Получить персонализированную ленту",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID целевого пользователя (только для admin)",
                        "name": "userUuid",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Лимит (1..100), по умолчанию 50",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Смещение, по умолчанию 0",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Окно выдачи в часах",
                        "name": "fromHours",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "FTS запрос (websearch syntax)",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Персонализированная лента",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_handlers_personalization.FeedItemResponseSchema"
                            }
                        }
                    },
                    "400": {
                        "description": "Невалидные query-параметры",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_personalization.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_personalization.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Недостаточно прав",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_personalization.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_personalization.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает всех пользователей из таблицы users, включая мягко удалённых. Требуется роль admin.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Получить список всех пользователей (только admin)",
                "responses": {
                    "200": {
                        "description": "Список пользователей",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/user.Response"
                            }
                        }
                    },
                    "401": {
                        "description": "Не авторизован - отсутствует или невалидный JWT токен",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_user.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Доступ запрещён - требуется роль admin",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_user.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_user.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Создаёт нового пользователя. UUID и email должны быть уникальными.\nДоступно для роли admin или service-account (для service-to-service\nкоммуникации между Auth-Proxy и Main Service).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Создать пользователя (admin или service account)",
                "parameters": [
                    {
                        "description": "Данные нового пользователя",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": ""
                    },
                    "400": {
                        "description": "Невалидный запрос или ошибка валидации",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_user.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Не авторизован - отсутствует или невалидный JWT токен",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_user.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Доступ запрещён - требуется роль admin или service-account",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_user.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_user.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/me/preferences": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает настройки personalization для текущего пользователя (роль user/admin).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "personalization"
                ],
                "summary": "Получить предпочтения пользователя",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID целевого пользователя (только для admin)",
                        "name": "userUuid",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Предпочтения пользователя",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_personalization.PreferencesResponseSchema"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_personalization.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Недостаточно прав",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_personalization.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_personalization.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Создает или обновляет настройки personalization текущего пользователя (роль user/admin).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "personalization"
                ],
                "summary": "Обновить предпочтения пользователя",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID целевого пользователя (только для admin)",
                        "name": "userUuid",
                        "in": "query"
                    },
                    {
                        "description": "Настройки personalization",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_personalization.UpdatePreferencesRequestSchema"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    },
                    "400": {
                        "description": "Невалидный payload",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_personalization.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_personalization.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Недостаточно прав",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_personalization.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_personalization.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{uuid}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает данные пользователя по UUID. Мягко удалённый вернётся с deleted=true. Требуется роль admin.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Получить пользователя (только admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID пользователя (формат: uuid4)",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Данные пользователя",
                        "schema": {
                            "$ref": "#/definitions/user.Response"
                        }
                    },
                    "400": {
                        "description": "Невалидный UUID",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_user.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Не авторизован - отсутствует или невалидный JWT токен",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_user.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Доступ запрещён - недостаточно прав (требуется роль admin)",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_user.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_user.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_user.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Мягкое удаление (soft delete). Запись остаётся в БД с флагом deleted=true. Требуется роль admin.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Удалить пользователя (только admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID пользователя (формат: uuid4)",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Пользователь успешно удалён"
                    },
                    "400": {
                        "description": "Невалидный UUID",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_user.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Не авторизован - отсутствует или невалидный JWT токен",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_user.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Доступ запрещён - недостаточно прав (требуется роль admin)",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_user.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_user.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers_user.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/news.v1.NewsService/SaveProcessedNews": {
            "post": {
                "responses": {}
            }
        },
        "/news_sources.v1.NewsSourcesService/GetNewsSources": {
            "post": {
                "responses": {}
            }
        }
    },
    "definitions": {
        "github.com_FischukSergey_otus-ms_internal_handlers_newshttp.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "github.com_FischukSergey_otus-ms_internal_handlers_newshttp.NewsResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "topic": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "github.com_FischukSergey_otus-ms_internal_handlers_personalization.CreateEventRequestSchema": {
            "type": "object",
            "properties": {
                "eventType": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "any"
                    }
                },
                "newsId": {
                    "type": "string"
                }
            }
        },
        "github.com_FischukSergey_otus-ms_internal_handlers_personalization.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "github.com_FischukSergey_otus-ms_internal_handlers_personalization.FeedItemResponseSchema": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "processedAt": {
                    "type": "string"
                },
                "publishedAt": {
                    "type": "string"
                },
                "score": {
                    "type": "number"
                },
                "source": {
                    "type": "string"
                },
                "sourceId": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "topic": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "github.com_FischukSergey_otus-ms_internal_handlers_personalization.PreferencesResponseSchema": {
            "type": "object",
            "properties": {
                "fromHours": {
                    "type": "integer"
                },
                "preferredCategories": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "preferredKeywords": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "preferredLanguage": {
                    "type": "string"
                },
                "preferredSources": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github.com_FischukSergey_otus-ms_internal_handlers_personalization.UpdatePreferencesRequestSchema": {
            "type": "object",
            "properties": {
                "fromHours": {
                    "type": "integer"
                },
                "preferredCategories": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "preferredKeywords": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "preferredLanguage": {
                    "type": "string"
                },
                "preferredSources": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "github.com_FischukSergey_otus-ms_internal_handlers_user.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "internal_handlers_newshttp.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "internal_handlers_newshttp.NewsResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "topic": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "internal_handlers_personalization.CreateEventRequestSchema": {
            "type": "object",
            "properties": {
                "eventType": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "any"
                    }
                },
                "newsId": {
                    "type": "string"
                }
            }
        },
        "internal_handlers_personalization.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "internal_handlers_personalization.FeedItemResponseSchema": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "processedAt": {
                    "type": "string"
                },
                "publishedAt": {
                    "type": "string"
                },
                "score": {
                    "type": "number"
                },
                "source": {
                    "type": "string"
                },
                "sourceId": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "topic": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "internal_handlers_personalization.PreferencesResponseSchema": {
            "type": "object",
            "properties": {
                "fromHours": {
                    "type": "integer"
                },
                "preferredCategories": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "preferredKeywords": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "preferredLanguage": {
                    "type": "string"
                },
                "preferredSources": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "internal_handlers_personalization.UpdatePreferencesRequestSchema": {
            "type": "object",
            "properties": {
                "fromHours": {
                    "type": "integer"
                },
                "preferredCategories": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "preferredKeywords": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "preferredLanguage": {
                    "type": "string"
                },
                "preferredSources": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "internal_handlers_user.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "user.CreateRequest": {
            "type": "object",
            "required": [
                "email",
                "uuid"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 255
                },
                "firstName": {
                    "type": "string",
                    "maxLength": 255
                },
                "lastName": {
                    "type": "string",
                    "maxLength": 255
                },
                "middleName": {
                    "type": "string",
                    "maxLength": 255
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "user.Response": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deleted": {
                    "type": "boolean"
                },
                "deletedAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "middleName": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "fishouk-otus-ms.ru",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "OtusMS Main Service API",
	Description:      "Введите: Bearer {токен} — с префиксом и пробелом.\nТокен: POST /api/v1/auth/login. Роли в claim realm_access.roles",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
