// Package authproxy GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package authproxy

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "OtusMS Support",
            "url": "https://github.com/FischukSergey/otus-ms"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/login": {
            "post": {
                "responses": {}
            }
        },
        "/api/v1/auth/logout": {
            "post": {
                "responses": {}
            }
        },
        "/api/v1/auth/refresh": {
            "post": {
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "fishouk-otus-ms.ru",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "OtusMS Auth-Proxy API",
	Description:      "API для аутентификации пользователей через Keycloak в проекте OtusMS.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
