// Package authproxy GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package authproxy

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "OtusMS Support",
            "url": "https://github.com/FischukSergey/otus-ms"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/login": {
            "post": {
                "description": "Аутентифицирует пользователя и возвращает access и refresh токены.\nТокены получаются от Keycloak.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Вход в систему",
                "parameters": [
                    {
                        "description": "Учетные данные пользователя",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/keycloak.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Токены успешно получены",
                        "schema": {
                            "$ref": "#/definitions/keycloak.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "Невалидный запрос или отсутствуют обязательные поля",
                        "schema": {
                            "$ref": "#/definitions/keycloak.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Неверные учетные данные",
                        "schema": {
                            "$ref": "#/definitions/keycloak.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера или ошибка Keycloak",
                        "schema": {
                            "$ref": "#/definitions/keycloak.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/logout": {
            "post": {
                "description": "Инвалидирует refresh токен в Keycloak, завершая сессию пользователя.\nПосле logout токены становятся недействительными.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Выход из системы",
                "parameters": [
                    {
                        "description": "Refresh токен для инвалидации",
                        "name": "token",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/keycloak.LogoutRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Выход выполнен успешно"
                    },
                    "400": {
                        "description": "Невалидный запрос или отсутствует refresh token",
                        "schema": {
                            "$ref": "#/definitions/keycloak.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка при выполнении logout в Keycloak",
                        "schema": {
                            "$ref": "#/definitions/keycloak.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/refresh": {
            "post": {
                "description": "Обменивает refresh токен на новую пару access и refresh токенов.\nПозволяет продлить сессию пользователя без повторного ввода пароля.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Обновление токена",
                "parameters": [
                    {
                        "description": "Refresh токен",
                        "name": "token",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/keycloak.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Новые токены успешно получены",
                        "schema": {
                            "$ref": "#/definitions/keycloak.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "Невалидный запрос или отсутствует refresh token",
                        "schema": {
                            "$ref": "#/definitions/keycloak.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Невалидный или истекший refresh токен",
                        "schema": {
                            "$ref": "#/definitions/keycloak.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера или ошибка Keycloak",
                        "schema": {
                            "$ref": "#/definitions/keycloak.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/register": {
            "post": {
                "description": "Создаёт пользователя в Keycloak и Main Service с ролью user.\nПосле регистрации необходимо выполнить login для получения токенов.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Регистрация нового пользователя",
                "parameters": [
                    {
                        "description": "Данные для регистрации",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/keycloak.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Пользователь успешно зарегистрирован"
                    },
                    "400": {
                        "description": "Невалидные данные или ошибка валидации",
                        "schema": {
                            "$ref": "#/definitions/keycloak.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Пользователь с таким email уже существует",
                        "schema": {
                            "$ref": "#/definitions/keycloak.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/keycloak.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "keycloak.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "error_description": {
                    "type": "string"
                }
            }
        },
        "keycloak.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "keycloak.LogoutRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "keycloak.RefreshRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "keycloak.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "firstName",
                "lastName",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 255
                },
                "firstName": {
                    "type": "string",
                    "maxLength": 255
                },
                "lastName": {
                    "type": "string",
                    "maxLength": 255
                },
                "middleName": {
                    "type": "string",
                    "maxLength": 255
                },
                "password": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 8
                }
            }
        },
        "keycloak.TokenResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "refresh_expires_in": {
                    "type": "integer"
                },
                "refresh_token": {
                    "type": "string"
                },
                "scope": {
                    "type": "string"
                },
                "token_type": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it.
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "fishouk-otus-ms.ru",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "OtusMS Auth-Proxy API",
	Description:      "API для аутентификации пользователей через Keycloak в проекте OtusMS.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
