basePath: /
host: fishouk-otus-ms.ru
info:
  contact:
    name: OtusMS Support
    url: https://github.com/FischukSergey/otus-ms
  description: API для аутентификации пользователей через Keycloak в проекте OtusMS.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: OtusMS Auth-Proxy API
  version: 1.0.0
paths:
  /api/v1/auth/login:
    post:
      responses: {}
  /api/v1/auth/logout:
    post:
      responses: {}
  /api/v1/auth/refresh:
    post:
      responses: {}
swagger: "2.0"
