name: otusms  # Уникальное имя проекта, чтобы избежать конфликтов

services:
  postgres:
    container_name: otusms-postgres-local
    image: postgres:16-alpine
    profiles:
      - db  # Запускается с профилем: docker compose --profile db up
    restart: unless-stopped
    ports:
      - "38432:5432"
    environment:
      - POSTGRES_DB=otus_ms
      - POSTGRES_USER=otus_ms
      - POSTGRES_PASSWORD=otus_ms
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - otusms_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U otus_ms -d otus_ms"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  otusms_network:
    name: otusms_local_network
    driver: bridge

volumes:
  postgres_data:
    name: otusms_postgres_data_local

