// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: news_sources/v1/news_sources.proto

package news_sourcesv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NewsSourcesService_GetNewsSources_FullMethodName = "/news_sources.v1.NewsSourcesService/GetNewsSources"
)

// NewsSourcesServiceClient is the client API for NewsSourcesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NewsSourcesService предоставляет доступ к источникам новостей.
type NewsSourcesServiceClient interface {
	// GetNewsSources возвращает список всех активных источников новостей.
	GetNewsSources(ctx context.Context, in *GetNewsSourcesRequest, opts ...grpc.CallOption) (*GetNewsSourcesResponse, error)
}

type newsSourcesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNewsSourcesServiceClient(cc grpc.ClientConnInterface) NewsSourcesServiceClient {
	return &newsSourcesServiceClient{cc}
}

func (c *newsSourcesServiceClient) GetNewsSources(ctx context.Context, in *GetNewsSourcesRequest, opts ...grpc.CallOption) (*GetNewsSourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNewsSourcesResponse)
	err := c.cc.Invoke(ctx, NewsSourcesService_GetNewsSources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NewsSourcesServiceServer is the server API for NewsSourcesService service.
// All implementations must embed UnimplementedNewsSourcesServiceServer
// for forward compatibility.
//
// NewsSourcesService предоставляет доступ к источникам новостей.
type NewsSourcesServiceServer interface {
	// GetNewsSources возвращает список всех активных источников новостей.
	GetNewsSources(context.Context, *GetNewsSourcesRequest) (*GetNewsSourcesResponse, error)
	mustEmbedUnimplementedNewsSourcesServiceServer()
}

// UnimplementedNewsSourcesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNewsSourcesServiceServer struct{}

func (UnimplementedNewsSourcesServiceServer) GetNewsSources(context.Context, *GetNewsSourcesRequest) (*GetNewsSourcesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNewsSources not implemented")
}
func (UnimplementedNewsSourcesServiceServer) mustEmbedUnimplementedNewsSourcesServiceServer() {}
func (UnimplementedNewsSourcesServiceServer) testEmbeddedByValue()                            {}

// UnsafeNewsSourcesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NewsSourcesServiceServer will
// result in compilation errors.
type UnsafeNewsSourcesServiceServer interface {
	mustEmbedUnimplementedNewsSourcesServiceServer()
}

func RegisterNewsSourcesServiceServer(s grpc.ServiceRegistrar, srv NewsSourcesServiceServer) {
	// If the following call panics, it indicates UnimplementedNewsSourcesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NewsSourcesService_ServiceDesc, srv)
}

func _NewsSourcesService_GetNewsSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNewsSourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsSourcesServiceServer).GetNewsSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsSourcesService_GetNewsSources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsSourcesServiceServer).GetNewsSources(ctx, req.(*GetNewsSourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NewsSourcesService_ServiceDesc is the grpc.ServiceDesc for NewsSourcesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NewsSourcesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "news_sources.v1.NewsSourcesService",
	HandlerType: (*NewsSourcesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNewsSources",
			Handler:    _NewsSourcesService_GetNewsSources_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "news_sources/v1/news_sources.proto",
}
