// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: news_sources/v1/news_sources.proto

package news_sourcesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetNewsSourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNewsSourcesRequest) Reset() {
	*x = GetNewsSourcesRequest{}
	mi := &file_news_sources_v1_news_sources_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNewsSourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewsSourcesRequest) ProtoMessage() {}

func (x *GetNewsSourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_news_sources_v1_news_sources_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewsSourcesRequest.ProtoReflect.Descriptor instead.
func (*GetNewsSourcesRequest) Descriptor() ([]byte, []int) {
	return file_news_sources_v1_news_sources_proto_rawDescGZIP(), []int{0}
}

type NewsSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	FetchInterval int32                  `protobuf:"varint,6,opt,name=fetch_interval,json=fetchInterval,proto3" json:"fetch_interval,omitempty"`
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewsSource) Reset() {
	*x = NewsSource{}
	mi := &file_news_sources_v1_news_sources_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewsSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewsSource) ProtoMessage() {}

func (x *NewsSource) ProtoReflect() protoreflect.Message {
	mi := &file_news_sources_v1_news_sources_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewsSource.ProtoReflect.Descriptor instead.
func (*NewsSource) Descriptor() ([]byte, []int) {
	return file_news_sources_v1_news_sources_proto_rawDescGZIP(), []int{1}
}

func (x *NewsSource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NewsSource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NewsSource) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *NewsSource) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *NewsSource) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *NewsSource) GetFetchInterval() int32 {
	if x != nil {
		return x.FetchInterval
	}
	return 0
}

func (x *NewsSource) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type GetNewsSourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sources       []*NewsSource          `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNewsSourcesResponse) Reset() {
	*x = GetNewsSourcesResponse{}
	mi := &file_news_sources_v1_news_sources_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNewsSourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewsSourcesResponse) ProtoMessage() {}

func (x *GetNewsSourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_news_sources_v1_news_sources_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewsSourcesResponse.ProtoReflect.Descriptor instead.
func (*GetNewsSourcesResponse) Descriptor() ([]byte, []int) {
	return file_news_sources_v1_news_sources_proto_rawDescGZIP(), []int{2}
}

func (x *GetNewsSourcesResponse) GetSources() []*NewsSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

var File_news_sources_v1_news_sources_proto protoreflect.FileDescriptor

const file_news_sources_v1_news_sources_proto_rawDesc = "" +
	"\n" +
	"\"news_sources/v1/news_sources.proto\x12\x0fnews_sources.v1\"\x17\n" +
	"\x15GetNewsSourcesRequest\"\xbe\x01\n" +
	"\n" +
	"NewsSource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12%\n" +
	"\x0efetch_interval\x18\x06 \x01(\x05R\rfetchInterval\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\"O\n" +
	"\x16GetNewsSourcesResponse\x125\n" +
	"\asources\x18\x01 \x03(\v2\x1b.news_sources.v1.NewsSourceR\asources2w\n" +
	"\x12NewsSourcesService\x12a\n" +
	"\x0eGetNewsSources\x12&.news_sources.v1.GetNewsSourcesRequest\x1a'.news_sources.v1.GetNewsSourcesResponseBEZCgithub.com/FischukSergey/otus-ms/pkg/news_sources/v1;news_sourcesv1b\x06proto3"

var (
	file_news_sources_v1_news_sources_proto_rawDescOnce sync.Once
	file_news_sources_v1_news_sources_proto_rawDescData []byte
)

func file_news_sources_v1_news_sources_proto_rawDescGZIP() []byte {
	file_news_sources_v1_news_sources_proto_rawDescOnce.Do(func() {
		file_news_sources_v1_news_sources_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_news_sources_v1_news_sources_proto_rawDesc), len(file_news_sources_v1_news_sources_proto_rawDesc)))
	})
	return file_news_sources_v1_news_sources_proto_rawDescData
}

var file_news_sources_v1_news_sources_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_news_sources_v1_news_sources_proto_goTypes = []any{
	(*GetNewsSourcesRequest)(nil),  // 0: news_sources.v1.GetNewsSourcesRequest
	(*NewsSource)(nil),             // 1: news_sources.v1.NewsSource
	(*GetNewsSourcesResponse)(nil), // 2: news_sources.v1.GetNewsSourcesResponse
}
var file_news_sources_v1_news_sources_proto_depIdxs = []int32{
	1, // 0: news_sources.v1.GetNewsSourcesResponse.sources:type_name -> news_sources.v1.NewsSource
	0, // 1: news_sources.v1.NewsSourcesService.GetNewsSources:input_type -> news_sources.v1.GetNewsSourcesRequest
	2, // 2: news_sources.v1.NewsSourcesService.GetNewsSources:output_type -> news_sources.v1.GetNewsSourcesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_news_sources_v1_news_sources_proto_init() }
func file_news_sources_v1_news_sources_proto_init() {
	if File_news_sources_v1_news_sources_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_news_sources_v1_news_sources_proto_rawDesc), len(file_news_sources_v1_news_sources_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_news_sources_v1_news_sources_proto_goTypes,
		DependencyIndexes: file_news_sources_v1_news_sources_proto_depIdxs,
		MessageInfos:      file_news_sources_v1_news_sources_proto_msgTypes,
	}.Build()
	File_news_sources_v1_news_sources_proto = out.File
	file_news_sources_v1_news_sources_proto_goTypes = nil
	file_news_sources_v1_news_sources_proto_depIdxs = nil
}
