// Code generated by options-gen. DO NOT EDIT.
package store

type OptOptionsSetter func(o *Options)

func NewOptions(
	dbName string,
	dbUser string,
	dbPassword string,
	dbHost string,
	dbPort string,
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)
	o.dbSSLMode = "disable"

	o.dbName = dbName

	o.dbUser = dbUser

	o.dbPassword = dbPassword

	o.dbHost = dbHost

	o.dbPort = dbPort

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithDbSSLMode(opt string) OptOptionsSetter {
	return func(o *Options) {
		o.dbSSLMode = opt

	}
}

func WithDbSSLRootCert(opt string) OptOptionsSetter {
	return func(o *Options) {
		o.dbSSLRootCert = opt

	}
}

func WithDbSSLKey(opt string) OptOptionsSetter {
	return func(o *Options) {
		o.dbSSLKey = opt

	}
}

func (o *Options) Validate() error {
	return nil
}
