global:
  env: local

log:
  level: info
  format: json
  service_name: main-service

servers:
  debug:
    addr: "127.0.0.1:6060"
  client:
    addr: "127.0.0.1:8080"
    allow_origins:
      - "*"
  metrics:
    addr: "127.0.0.1:9090"

db:
  name: otus_ms_test
  user: otus_ms_test
  password: otus_ms_test
  host: localhost
  port: "38433"
  ssl_mode: disable

jwt:
  skip_verify: true  # Тестовый режим - не проверять подпись JWT
  issuer: ""  # Не проверять issuer в тестовом режиме (принимаем токены от Keycloak)
  audience: ""  # Не проверять audience в тестовом режиме

